name: Blocked-In-Combat
main: me.chengzhify.blockedInCombat.BlockedInCombat
version: 1.0.0
api-version: '1.21'
authors: [ChengZhiFy]
description: Blocked In Combat minigame

commands:
  bic:
    description: Main command of BlockedInCombat
    usage: /bic <start|forcestart|stop|team|status|menu|setlobby|reload>

permissions:
  bic.admin:
    description: Admin permission for Blocked-In-Combat
    default: op
